databases:
  - name: icbp-db  # Changed from erp_db
    databaseName: icbp_db
    user: icbp_db_user

services:
  - type: web
    name: icbp-git
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn erp_core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: icbp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
