# Generated by Django 5.0.14 on 2026-04-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_user_client_subtype_user_client_type_user_staff_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('return_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('FILED', 'Filed')], default='NOT_STARTED', max_length=50)),
                ('due_date', models.DateField()),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('tax_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='tax.taxreturn')),
            ],
        ),
    ]
