"""
Django settings for erp_core project.
Generated by 'django-admin startproject' using Django 5.0.14.
"""

from pathlib import Path
import dj_database_url
import os
import sys
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-cxua=o!r^qgz8h4=n!-kthn!l8#gfhc3ptoi(qr-zlwh4$b@xn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.sites', # Required by allauth
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.openid_connect',
    'erp_core',
    'base',
    'audit',
    'tax',
    'ledger',
]

SITE_ID = 1  # Required by allauth & django.contrib.sites
AUTH_USER_MODEL = 'base.User'
TENANT_MODEL = 'base.Tenant'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ── django-allauth (v0.63+ settings) ─────────────────────────────────────────
ACCOUNT_EMAIL_VERIFICATION = 'none'           # set to 'mandatory' in production
ACCOUNT_LOGIN_METHODS = {'email'}             # replaces ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # replaces EMAIL_REQUIRED / USERNAME_REQUIRED
ACCOUNT_UNIQUE_EMAIL = True

# Custom adapters for role-based redirect (STAFF → /staff/dashboard, CLIENT → /client/dashboard)
ACCOUNT_ADAPTER = 'erp_core.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'erp_core.adapters.SocialAccountAdapter'

# After OAuth, our custom view (oauth_complete) issues JWTs and redirects to React
LOGIN_REDIRECT_URL = '/accounts/oauth-complete/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/login'
SOCIALACCOUNT_LOGIN_ON_GET = True   # Skip allauth's "do you want to connect?" page
SOCIALACCOUNT_AUTO_SIGNUP = True    # Skip the email-confirmation sign-up form for new social logins

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
    },
    'openid_connect': {
        'APPS': [
            {
                # LinkedIn OIDC — discovery doc at:
                # https://www.linkedin.com/oauth/.well-known/openid-configuration
                'provider_id': 'linkedin',
                'name': 'LinkedIn',
                'client_id': os.environ.get('LINKEDIN_CLIENT_ID', ''),
                'secret':    os.environ.get('LINKEDIN_CLIENT_SECRET', ''),
                'settings': {
                    'server_url': 'https://www.linkedin.com/oauth',
                },
            },
        ],
    },
}


# dj-rest-auth uses JWT
REST_USE_JWT = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required by allauth
]

CORS_ALLOW_ALL_ORIGINS = True 

ROOT_URLCONF = 'erp_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Secure cookies: True in production (HTTPS), False in local dev (HTTP)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

WSGI_APPLICATION = 'erp_core.wsgi.application'

# DATABASE CONFIGURATION
# If we are testing OR if no DATABASE_URL is found in the environment, use SQLite locally.
# Render automatically provides DATABASE_URL, so it will use Postgres there.
if 'test' in sys.argv or not os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=True  # This is the critical fix for Render
        )
    }
    # Add this right below the DATABASES definition to be 100% safe
    # DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
