# Generated by Django 5.0.14 on 2026-04-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_user_client_subtype_user_client_type_user_staff_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('financial_year_end', models.DateField()),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('FIELDWORK', 'Fieldwork'), ('REVIEW', 'Review'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=50)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_engagements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audit/working_papers/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_REVIEW', 'Ready for Review'), ('REVIEWED', 'Reviewed'), ('SIGNED_OFF', 'Signed Off')], default='DRAFT', max_length=50)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_papers', to='audit.engagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_papers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
